zmConfig = {
	BASE_URL: "/",
	PROFILE_URL: "http://me.zing.vn/u",
	IMAGE_URL: "http://static.me.zing.vn",
        FRIEND_URL: 'http://me.zing.vn/jfr',
	SUGGESTION_URL: 'http://suggestion.me.zing.vn',
	NOTIFY_URL: 'http://privatemsg.me.zing.vn',	
	ME_URL: 'http://me.zing.vn',
	/** ME STATUS **/
	LINK_URL: 'http://link.apps.zing.vn',
	PHOTO_URL: 'http://photo.me.zing.vn',
	PHOTO_UPLOAD: 'http://photo.me.zing.vn',
	QA_URL: 'http://qa.apps.zing.vn',
	PRODUCT_FEED_ID: '160',
	APP_PHOTO_COMMENT_ID: '2',
	APP_PHOTO_WALL_ID: '149',
	APP_LINK_COMMENT_ID: '26',
	APP_LINK_WALL_ID: '128',
	APP_LINK_CATE_ID: '8',
	STATUS_VERSION: '1.01',
	FLOWER_SVC: 'http://flower.apps.zing.vn/FlowerServer/FlowerServ',	
	ZMSG_URL: 'http://privatemessage.me.zing.vn/v3',
	FULLPROFILE_URL: 'http://p.widget.me.zing.vn',
	MINIPROFILE_URL: 'http://widget.me.zing.vn',
	FLOWER_ALLOW_DOMAIN: 'me.zing.vn,me.zing.vn,me.zing.vn,me3.zing.vn',
	FLOWER_ENV: '',
	zme_avatar_tag: 'span',
	wg_profile_link: '/p/'
	
};
