/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "BackendMiddleware_constants.h"

namespace BackendMiddleware {

const BackendMiddlewareConstants g_BackendMiddleware_constants;

BackendMiddlewareConstants::BackendMiddlewareConstants() {
}

} // namespace

