/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BackendMiddleware_CONSTANTS_H
#define BackendMiddleware_CONSTANTS_H

#include "BackendMiddleware_types.h"

namespace BackendMiddleware {

class BackendMiddlewareConstants {
 public:
  BackendMiddlewareConstants();

};

extern const BackendMiddlewareConstants g_BackendMiddleware_constants;

} // namespace

#endif
